AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS VPC + Amazon Relational Database Service (Amazon RDS) for PostgreSQL.
  (qs-1saaatk1o)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - KeyPairName
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
      - Label:
          default: Linux bastion configuration
        Parameters:
          - EnableBastion
          - RemoteAccessCIDR
          - EnableTCPForwarding
      - Label:
          default: Database configuration
        Parameters:
          - DBName
          - DBAccessCIDR
          - DBAutoMinorVersionUpgrade
          - DBAllowMajorVersionUpgrade
          - DBBackupRetentionPeriod
          - DBEngineVersion
          - DBInstanceClass
          - DBUsername
          - DBPassword
          - DBPort
          - DBAllocatedStorage
          - DBMaxAllocatedStorage
          - DBStorageType
          - DBIops
          - DBAllocatedStorageEncrypted
          - DBExportLogToCloudwatch
          - DBMultiAZ
          - DBMonitoringInterval
          - EnableEventSubscription
          - NotificationList
      - Label:
          default: Database tags (optional)
        Parameters:
          - EnvironmentStage
          - Application
          - ApplicationVersion
          - ProjectCostCenter
          - Confidentiality
          - Compliance
      - Label:
          default: AWS Partner Solution configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      DBAllocatedStorage:
        default: Amount of storage (in gigabytes)
      DBMaxAllocatedStorage:
        default: Maximum allocated storage
      DBStorageType:
        default: Storage type
      DBIops:
        default: IOPS
      AvailabilityZones:
        default: Availability Zones
      DBEngineVersion:
        default: Engine version
      DBName:
        default: Name
      DBAllocatedStorageEncrypted:
        default: Enable encryption
      DBExportLogToCloudwatch:
        default: Export database log to CloudWatch
      DBAutoMinorVersionUpgrade:
        default: Database auto minor version upgrade
      DBAllowMajorVersionUpgrade:
        default: Database allow major version upgrade
      DBBackupRetentionPeriod:
        default: Database backup retention period
      DBInstanceClass:
        default: Database instance class
      DBUsername:
        default: User name
      DBPassword:
        default: Password
      DBPort:
        default: Port
      DBAccessCIDR:
        default: Database connection CIDR
      DBMultiAZ:
        default: Multi-AZ deployment
      DBMonitoringInterval:
        default: Monitoring interval
      EnableBastion:
        default: Create bastion stack
      EnableTCPForwarding:
        default: Enable TCP forwarding
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      QSS3BucketName:
        default: Partner Solution S3 bucket name
      QSS3BucketRegion:
        default: Partner Solution S3 bucket Region
      QSS3KeyPrefix:
        default: Partner Solution S3 key prefix
      VPCCIDR:
        default: VPC CIDR
      EnableEventSubscription:
        default: Enable event subscription
      NotificationList:
        default: Amazon SNS notification email
      EnvironmentStage:
        default: Environment stage
      Application:
        default: Application name
      ApplicationVersion:
        default: Application version
      Compliance:
        default: Compliance classifier
      Confidentiality:
        default: Confidentiality classifier
      ProjectCostCenter:
        default: Project cost center
      KeyPairName:
        default: Key name
      RemoteAccessCIDR:
        default: Permitted IP range
Parameters:
  AvailabilityZones:
   Type: List<AWS::EC2::AvailabilityZone::Name>
   Description: >-
      List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: >-
      Name of an existing public/private key pair used to connect to your
      instance.
    ConstraintDescription: Name of an existing Amazon EC2 key pair.
  PrivateSubnet1CIDR:
    Type: String
    Description: >-
      CIDR block for private subnet 1 located in Availability Zone 1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.0.0/19
  PrivateSubnet2CIDR:
    Type: String
    Description: >-
      CIDR block for private subnet 2 located in Availability Zone 2.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.32.0/19
  PublicSubnet1CIDR:
    Type: String
    Description: >-
      CIDR block for the public subnet 1 located in Availability Zone 1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.128.0/20
  PublicSubnet2CIDR:
    Type: String
    Description: >-
      CIDR block for the public subnet 2 located in Availability Zone 2.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.144.0/20
  RemoteAccessCIDR:
    Type: String
    Description: Allowed CIDR block for external SSH access.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x.
    Default: 10.0.0.0/16
  VPCCIDR:
    Type: String
    Description: CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.0.0/16
  QSS3BucketName:
    Type: String
    Description: >-
      Name of the S3 bucket for your copy of the deployment assets. Keep the default
      name unless you are customizing the template. Changing the name updates code 
      references to point to a new location.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: >-
      The S3 bucket name can include numbers, lowercase letters, 
      and hyphens (-), but it cannot start or end with a hyphen.
    Default: aws-quickstart
  QSS3BucketRegion:
    Type: String
    Description: >-
      AWS Region where the S3 bucket (QSS3BucketName) is hosted. Keep 
      the default Region unless you are customizing the template. Changing the Region 
      updates code references to point to a new location. When using your own bucket, 
      specify the Region.
    Default: us-east-1
  QSS3KeyPrefix:
    Type: String
    Description: >-
      S3 key prefix that is used to simulate a folder for your copy of the 
      deployment assets. Keep the default prefix unless you are customizing 
      the template. Changing the prefix updates code references to point to 
      a new location.
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: >-
      The S3 key prefix can include numbers, lowercase letters, uppercase letters, 
      hyphens (-), underscores (_), periods (.), asterisks (*), single quotes ('),
      open parenthesis ((), close parenthesis ()), and forward slashes (/). End the
      prefix with a forward slash.
    Default: quickstart-amazon-rds-postgres/
  EnableBastion:
    Type: String
    Description: If true, creates a bastion stack.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBAllocatedStorage:
    Type: Number
    Description: Amount of storage (in gigabytes).
    Default: 100
  DBMaxAllocatedStorage:
    Type: Number
    Description: >-
      The upper limit in gigabytes to which Amazon RDS can automatically scale
      the storage.
    Default: 1000
  DBAllocatedStorageEncrypted:
    Type: String
    Description: Choose 'true' to encrypt the database.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBIops:
    Type: Number
    Description: Must be in the range of 1,000 - 256,000 IOPS.
    MinValue: 1000
    MaxValue: 256000
    ConstraintDescription: Must be in the range 1,000 - 256,000 IOPS.
    Default: 3000
  DBExportLogToCloudwatch:
    Type: String
    Description: Choose 'true' to export database logs to CloudWatch.
    AllowedValues: ['true', 'false']
    Default: 'true'
  EnableTCPForwarding:
    Type: String
    Description: Choose 'true' to enable TCP forwarding.
    AllowedValues: ['true', 'false']
    Default: 'false'
  DBAutoMinorVersionUpgrade:
    Type: String
    Description: Choose 'true' to set up auto minor version upgrade.
    AllowedValues: ['true', 'false']
    Default: 'false'
  DBAllowMajorVersionUpgrade:
    Type: String
    Description: Choose 'true' to set up major version upgrade.
    AllowedValues: ['true', 'false']
    Default: 'false'
  DBBackupRetentionPeriod:
    Type: Number
    Description: >-
      The number of days that automatic database snapshots are retained.
    MinValue: 0
    MaxValue: 35
    ConstraintDescription: >-
      Must be a value from 0 to 35. Can't be set to 0 if the database instance
      is a source to read replicas.
    Default: 35
  DBEngineVersion:
    Type: String
    Description: Select database engine version.
    AllowedValues:
      - 10.17
      - 10.18
      - 10.19
      - 10.20
      - 10.21
      - 11.12
      - 11.13
      - 11.14
      - 11.15
      - 11.16
      - 12.7
      - 12.8
      - 12.9
      - 12.10
      - 12.11
      - 13.3
      - 13.4
      - 13.5
      - 13.6
      - 13.7
      - 14.1
      - 14.2
      - 14.3
      - 14.4
    Default: 14.4
  DBInstanceClass:
    Type: String
    Description: >-
      The name of the compute and memory capacity class of the database
      instance.
    AllowedPattern: ^db\.[a-z0-9]+\.[a-z0-9]+$
    ConstraintDescription: Must select a valid database instance type.
    Default: db.m6g.large
  DBAccessCIDR:
    Type: String
    Description: Allowed CIDR block for external access (use VPC CIDR).
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x.
    Default: 10.0.0.0/16
  DBPassword:
    Type: String
    Description: The database administrator account password.
    MinLength: 8
    MaxLength: 128
    AllowedPattern: ^[^/'\"@]+$
    ConstraintDescription: >-
      Must be 8 to 128 printable ASCII characters. Can't contain any of the following:
      slash (/), single quote (''), double quote ("), or at sign (@).
    NoEcho: True
  DBUsername:
    Type: String
    Description: The database administrator account user name.
    MinLength: 1
    MaxLength: 16
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Default: pgadmin
  DBMonitoringInterval:
    Type: Number
    AllowedValues: [0, 1, 5, 15, 30, 60]
    Description: >-
      Enhanced monitoring metrics interval in seconds. To disable
      enhanced monitoring metrics, specify 0.
    Default: 60
  DBPort:
    Type: Number
    Description: The port used by the instance to listen for connections. 
    MinValue: 1150
    MaxValue: 65535
    ConstraintDescription: Must be in the range [1115-65535].
    Default: 5432
  DBMultiAZ:
    Type: String
    Description: >-
      Choose 'true' to deploy a multi-AZ database instance.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBName:
    Type: String
    Description: Name of the Amazon RDS (PostgreSQL) database.
    MinLength: 5
    MaxLength: 64
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*$
    Default: RDSPostgresDB
  DBStorageType:
    Type: String
    Description: >-
      Storage type. For additional information, refer to
      https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html.
    AllowedValues: [io1, gp2]
    Default: io1
  EnableEventSubscription:
    Type: String
    Description: Enables event subscription to notification list.
    AllowedValues: ['true', 'false']
    Default: 'true'
  NotificationList:
    Type: String
    Description: >-
      The email notification used to configure an Amazon SNS topic for sending
      CloudWatch alarm and Amazon RDS event notifications.
    AllowedPattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
    ConstraintDescription: Provide a valid email address.
    Default: db-ops@domain.com
  EnvironmentStage:
    Type: String
    Description: >-
      (Optional) Designates the environment stage of the associated AWS
      resource.
    AllowedValues:
      - dev
      - test
      - pre-prod
      - prod
      - none
    Default: none
  Application:
    Type: String
    Description: >-
      (Optional) Designates the application of the associated AWS resource.
    Default: ''
  ApplicationVersion:
    Type: String
    Description: (Optional) Designates the specific version of the application.
    Default: ''
  ProjectCostCenter:
    Type: String
    Default: ''
    Description: >-
      (Optional) Designates the cost center associated with the project of the
      given AWS resource.
  Confidentiality:
    Type: String
    Description: >-
      (Optional) Designates the confidentiality classification of the data that
      is associated with the resource.
    AllowedValues:
      - public
      - private
      - confidential
      - pii/phi
      - none
      - ''
    Default: ''
  Compliance:
    Type: String
    Description: >-
      (Optional) Designates the compliance level for the AWS resource.
    AllowedValues:
      - hipaa
      - sox
      - fips
      - other
      - ''
    Default: ''
Conditions:
  EnableBastionAccess: !Equals [!Ref EnableBastion, 'true']
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, aws-quickstart]
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join [',', !Ref AvailabilityZones]
        NumberOfAZs: 2
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/postgres-entrypoint-existing-vpc.template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        Subnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        Subnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        DBName: !Ref DBName
        DBAutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBStorageType: !Ref DBStorageType
        DBIops: !Ref DBIops
        DBAllowMajorVersionUpgrade: !Ref DBAllowMajorVersionUpgrade
        DBMaxAllocatedStorage: !Ref DBMaxAllocatedStorage
        DBAllocatedStorageEncrypted: !Ref DBAllocatedStorageEncrypted
        DBExportLogToCloudwatch: !Ref DBExportLogToCloudwatch
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBEngineVersion: !Ref DBEngineVersion
        DBInstanceClass: !Ref DBInstanceClass
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBMonitoringInterval: !Ref DBMonitoringInterval
        DBPort: !Ref DBPort
        DBMultiAZ: !Ref DBMultiAZ
        DBAccessCIDR: !Ref DBAccessCIDR
        EnableEventSubscription: !Ref EnableEventSubscription
        NotificationList: !Ref NotificationList
        EnvironmentStage: !Ref EnvironmentStage
        Application: !Ref Application
        ApplicationVersion: !Ref ApplicationVersion
        ProjectCostCenter: !Ref ProjectCostCenter
        Confidentiality: !Ref Confidentiality
        Compliance: !Ref Compliance
  BastionStack:
  # TODO: Move this into the existing VPC stack.
    Type: AWS::CloudFormation::Stack
    Condition: EnableBastionAccess
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion-entrypoint-existing-vpc.template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        KeyPairName: !Ref KeyPairName
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        EnableTCPForwarding: !Ref EnableTCPForwarding
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}submodules/quickstart-linux-bastion/
