AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Amazon Relational Database Service (Amazon RDS) for PostgreSQL.
  (qs-1saaatk22)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - VPCID
          - Subnet1ID
          - Subnet2ID
          - CustomDBSecurityGroup
      - Label:
          default: Database configuration
        Parameters:
          - DBName
          - DBAccessCIDR
          - DBAutoMinorVersionUpgrade
          - DBAllowMajorVersionUpgrade
          - DBBackupRetentionPeriod
          - DBEngineVersion
          - DBInstanceClass
          - DBUsername
          - DBPassword
          - DBPort
          - DBAllocatedStorage
          - DBMaxAllocatedStorage
          - DBStorageType
          - DBIops
          - DBAllocatedStorageEncrypted
          - DBExportLogToCloudwatch
          - DBMultiAZ
          - DBMonitoringInterval
          - EnableEventSubscription
          - NotificationList
      - Label:
          default: Database tags (optional)
        Parameters:
          - EnvironmentStage
          - Application
          - ApplicationVersion
          - ProjectCostCenter
          - Confidentiality
          - Compliance
    ParameterLabels:
      DBAllocatedStorage:
        default: Amount of storage (in gigabytes)
      DBMaxAllocatedStorage:
        default: Maximum allocated storage
      DBStorageType:
        default: Storage type
      DBIops:
        default: IOPS
      DBName:
        default: Database name
      DBEngineVersion:
        default: Database engine version
      DBAllocatedStorageEncrypted:
        default: Enable encryption
      DBExportLogToCloudwatch:
        default: Export database log to CloudWatch
      DBAutoMinorVersionUpgrade:
        default: Auto minor version upgrade
      DBAllowMajorVersionUpgrade:
        default: Database allow major version upgrade
      DBBackupRetentionPeriod:
        default: Backup retention period
      DBInstanceClass:
        default: Database instance class
      DBUsername:
        default: User name
      DBPassword:
        default: Password
      DBPort:
        default: Port
      DBAccessCIDR:
        default: Database connection CIDR
      DBMultiAZ:
        default: Multi-AZ deployment
      DBMonitoringInterval:
        default: Monitoring interval
      Subnet1ID:
        default: Private subnet 1 ID
      Subnet2ID:
        default: Private subnet 2 ID
      VPCID:
        default: VPC ID
      CustomDBSecurityGroup:
        default: Custom security group ID
      EnableEventSubscription:
        default: Enable event subscription
      NotificationList:
        default: Amazon SNS notification email
      EnvironmentStage:
        default: Environment stage
      Application:
        default: Application name
      ApplicationVersion:
        default: Application version
      Compliance:
        default: Compliance classifier
      Confidentiality:
       default: Confidentiality classifier
      ProjectCostCenter:
       default: Project cost center
Mappings:
  DBFamilyMap:
    '10.17':
      family: postgres10
    '10.18':
      family: postgres10
    '10.19':
      family: postgres10
    '10.20':
      family: postgres10
    '10.21':
      family: postgres10
    '11.12':
      family: postgres11
    '11.13':
      family: postgres11
    '11.14':
      family: postgres11
    '11.15':
      family: postgres11
    '11.16':
      family: postgres11
    '12.7':
      family: postgres12
    '12.8':
      family: postgres12
    '12.9':
      family: postgres12
    '12.10':
      family: postgres12
    '12.11':
      family: postgres12
    '13.3':
      family: postgres13
    '13.4':
      family: postgres13
    '13.5':
      family: postgres13
    '13.6':
      family: postgres13
    '13.7':
      family: postgres13
    '14.1':
      family: postgres14
    '14.2':
      family: postgres14
    '14.3':
      family: postgres14
    '14.4':
      family: postgres14
Conditions:
  EventSubscription: !Equals [!Ref EnableEventSubscription, 'true']
  DoCreateDatabase: !Not [!Equals [!Ref DBName, '']]
  DBProvisionedIops: !Equals [!Ref DBStorageType, io1]
  UseEnhancedMonitoring: !Not [!Equals [!Ref DBMonitoringInterval, 0]]
  UseDatabaseEncryption: !Equals [!Ref DBAllocatedStorageEncrypted, 'true']
  EnableDBLogExport: !Equals [!Ref DBExportLogToCloudwatch, 'true']
  CreateSecurityGroup: !Equals [!Ref CustomDBSecurityGroup, '']
Parameters:
  DBAllocatedStorage:
    Type: Number
    Description: Amount of storage (in gigabytes).
    Default: 100
  DBMaxAllocatedStorage:
    Type: Number
    Description: >-
      The upper limit in gigabytes to which Amazon RDS can automatically scale
      the storage.
    Default: 1000
  DBAllocatedStorageEncrypted:
    Type: String
    Description: Choose 'true' to encrypt the database.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBIops:
    Type: Number
    Description: Must be in the range of 1,000 - 256,000 IOPS.
    MinValue: 1000
    MaxValue: 256000
    ConstraintDescription: Must be in the range 1,000 - 256,000 IOPS.
    Default: 3000
  DBExportLogToCloudwatch:
    Type: String
    Description: Choose 'true' to export database logs to Cloudwatch.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBAutoMinorVersionUpgrade:
    Type: String
    Description: Choose 'true' to set up automatic minor version upgrades.
    AllowedValues: ['true', 'false']
    Default: 'false'
  DBAllowMajorVersionUpgrade:
    Type: String
    Description: Choose 'true' to enable automatic major version upgrades.
    AllowedValues: ['true', 'false']
    Default: 'false'
  DBBackupRetentionPeriod:
    Type: Number
    Description: >-
      The number of days that automatic database snapshots are retained.
    MinValue: 0
    MaxValue: 35
    ConstraintDescription: >-
      Must be a value from 0 to 35. Can't be set to 0 if the database instance
      is a source to read replicas.
    Default: 35
  DBEngineVersion:
    Type: String
    Description: Choose database engine version.
    AllowedValues:
      - 10.17
      - 10.18
      - 10.19
      - 10.20
      - 10.21
      - 11.12
      - 11.13
      - 11.14
      - 11.15
      - 11.16
      - 12.7
      - 12.8
      - 12.9
      - 12.10
      - 12.11
      - 13.3
      - 13.4
      - 13.5
      - 13.6
      - 13.7
      - 14.1
      - 14.2
      - 14.3
      - 14.4
    Default: 14.4
  DBInstanceClass:
    Type: String
    Description: >-
      The name of the compute and memory capacity class of the database
      instance.
    AllowedPattern: ^db\.[a-z0-9]+\.[a-z0-9]+$
    ConstraintDescription: Must choose a valid database instance type.
    Default: db.m6g.large
  DBAccessCIDR:
    Type: String
    Description: Allowed CIDR block for external access (use VPC CIDR).
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x.
    Default: 10.0.0.0/16
  DBPassword:
    Type: String
    Description: The database administrator account password.
    AllowedPattern: ^[^/'\"@]+$
    ConstraintDescription: >-
      Must be 8 to 128 printable ASCII characters. Can't contain any of the following:
      slash (/), single quote (''), double quote ("), or at sign (@).
    MinLength: 8
    MaxLength: 128
    NoEcho: True
  DBUsername:
    Type: String
    Description: The database administrator account user name.
    MinLength: 1
    MaxLength: 16
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*$
    ConstraintDescription: >-
      Must begin with a letter and contain only alphanumeric characters.
    Default: pgadmin
  DBMonitoringInterval:
    Type: Number
    Description: >-
      Enhanced monitoring metrics interval in seconds. To disable
      enhanced monitoring metrics, specify 0.
    AllowedValues: [0, 1, 5, 15, 30, 60]
    Default: 60
  DBPort:
    Type: Number
    Description: The port used by the instance to listen for connections. 
    MinValue: 1150
    MaxValue: 65535
    ConstraintDescription: Must be in the range [1115-65535].
    Default: 5432
  DBMultiAZ:
    Type: String
    Description: >-
      Choose 'true' to deploy a multi-AZ database instance.
    AllowedValues: ['true', 'false']
    Default: 'true'
  DBName:
    Type: String
    Description: Name of the Amazon RDS (PostgreSQL) database.
    MinLength: 0
    MaxLength: 64
    AllowedPattern: ^[a-zA-Z0-9]*$
    Default: RDSPostgresDB
  DBStorageType:
    Type: String
    Description: >-
      Storage type. For additional information, see
      https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html.
    AllowedValues: [io1, gp2]
    Default: io1
  CustomDBSecurityGroup:
    Type: String
    Description: >-
      ID of the security group (example: sg-0234se). If left empty, a security group is created. 
    Default: ''
  Subnet1ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the private subnet in Availability Zone 1.
  Subnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the private subnet in Availability Zone 2.
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: >-
      ID of the VPC into which Amazon RDS (PostgreSQL) is deployed
      (example: vpc-0343606e).
    Default: ''
  EnableEventSubscription:
    Type: String
    Description: >-
      Choose 'true' to enable event subscription to notification list.
    AllowedValues: ['true', 'false']
    Default: 'true'
  NotificationList:
    Type: String
    Default: db-ops@domain.com
    Description: The email notification used to configure an Amazon SNS topic for sending CloudWatch alarm and Amazon RDS event notifications.
    AllowedPattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
    ConstraintDescription: Provide a valid email address.
  EnvironmentStage:
    Type: String
    Description: >-
      (Optional) Designates the environment stage of the associated AWS
      resource.
    AllowedValues:
      - dev
      - test
      - pre-prod
      - prod
      - none
    Default: none
  Application:
    Type: String
    Description: >-
      (Optional) Designates the application of the associated AWS resource.
    Default: ''
  ApplicationVersion:
    Type: String
    Description: (Optional) Designates the specific version of the application.
    Default: ''
  ProjectCostCenter:
    Type: String
    Description: >-
      (Optional) Designates the cost center associated with the project of the
      given AWS resource.
    Default: ''
  Confidentiality:
    Type: String
    Description: >-
      (Optional) Designates the confidentiality classification of the data that
      is associated with the resource.
    AllowedValues:
      - public
      - private
      - confidential
      - pii/phi
      - ''
    Default: ''
  Compliance:
    Type: String
    Description: (Optional) Designates the compliance level for the AWS resource.
    AllowedValues:
      - hipaa
      - sox
      - fips
      - other
      - ''
    Default: ''
Resources:
  MonitoringIAMRole:
    Type: AWS::IAM::Role
    Condition: UseEnhancedMonitoring
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
  DBSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationList
        Protocol: email
  EncryptionKey:
    Type: AWS::KMS::Key
    Condition: UseDatabaseEncryption
    DeletionPolicy: Retain
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - EIAMPolicyWildcardResource
            - EIAMPolicyActionWildcard
            - EKMSKeyEnableKeyRotation #Key rotation would cause the database to become inaccessible
            - W3011 # Partner Solutions need to be able to delete all assets upon stack deletion
      cfn_nag:
        rules_to_suppress:
          - id: F19
            reason: Key rotation causes the database to become inaccessible
          - id: F76
            reason: Conditions are included in the policy to limit its scope
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref AWS::StackName
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Condition: UseDatabaseEncryption
    Properties:
      AliasName: !Sub alias/${AWS::StackName}
      TargetKeyId: !Ref EncryptionKey
  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join ['- ', [RDS PostgreSQL Database Instance Parameter Group for Cloudformation Stack, !Ref DBName]]
      Family: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, family]
      Parameters:
        log_rotation_age: 1440
        log_rotation_size: 102400
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3011 # Partner Solutions need to be able to delete all assets upon stack deletion
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      AllowMajorVersionUpgrade: !Ref DBAllowMajorVersionUpgrade
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBParameterGroupName: !Ref DBParamGroup
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      EnableCloudwatchLogsExports:
        - !If [EnableDBLogExport, postgresql, !Ref AWS::NoValue]
      DBName: !If [DoCreateDatabase, !Ref DBName, !Ref AWS::NoValue]
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      KmsKeyId: !If [UseDatabaseEncryption, !GetAtt EncryptionKey.Arn, !Ref AWS::NoValue]
      MasterUserPassword: !Ref DBPassword
      MasterUsername: !Ref DBUsername
      MaxAllocatedStorage: !Ref DBMaxAllocatedStorage
      MonitoringInterval: !Ref DBMonitoringInterval
      MonitoringRoleArn: !If [UseEnhancedMonitoring, !GetAtt MonitoringIAMRole.Arn, !Ref AWS::NoValue]
      Port: !Ref DBPort
      PubliclyAccessible: false
      StorageType: !Ref DBStorageType
      Iops: !If [DBProvisionedIops, !Ref DBIops, !Ref AWS::NoValue]
      StorageEncrypted: !If [UseDatabaseEncryption, !Ref DBAllocatedStorageEncrypted, !Ref AWS::NoValue]
      MultiAZ: !Ref DBMultiAZ
      Tags:
        - Key: Name
          Value: !Sub RDSDB-${AWS::StackName}
        - Key: EnvironmentStage
          Value: !Ref EnvironmentStage
        - Key: Application
          Value: !Ref Application
        - Key: ApplicationVersion
          Value: !Ref ApplicationVersion
        - Key: ProjectCostCenter
          Value: !Ref ProjectCostCenter
        - Key: Confidentiality
          Value: !Ref Confidentiality
        - Key: Compliance
          Value: !Ref Compliance
      VPCSecurityGroups:
        - !If [CreateSecurityGroup, !Ref RDSSecurityGroup, !Ref CustomDBSecurityGroup]
    UpdateReplacePolicy: Snapshot
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: >-
        Subnets available for the Amazon RDS (PostgreSQL) database instance.
      SubnetIds:
       - !Ref Subnet1ID
       - !Ref Subnet2ID
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSecurityGroup
    Properties:
      GroupDescription: Allow access to database port.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: !Ref DBAccessCIDR
          FromPort: !Ref DBPort
          IpProtocol: tcp
          ToPort: !Ref DBPort
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub RDSSecurityGroup-${AWS::StackName}
  RDSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: CreateSecurityGroup
    Properties:
      GroupId: !GetAtt RDSSecurityGroup.GroupId
      IpProtocol: -1
      SourceSecurityGroupId: !Ref RDSSecurityGroup
      Description: Self Reference
  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: CPU_Utilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: CPUUtilization
      Statistic: Maximum
      Namespace: AWS/RDS
      Threshold: 80
      Unit: Percent
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  MaxUsedTxIDsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: Maximum used transaction IDs
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: MaximumUsedTransactionIDs
      Statistic: Average
      Namespace: AWS/RDS
      Threshold: 600000000
      Unit: Count
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  FreeLocalStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: Free Local Storage
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: FreeLocalStorage
      Statistic: Average
      Namespace: AWS/RDS
      Threshold: 5368709120
      Unit: Bytes
      ComparisonOperator: LessThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  DatabaseInstanceEventSubscription:
    Type: AWS::RDS::EventSubscription
    Condition: EventSubscription
    Properties:
      EventCategories:
      - availability
      - configuration change
      - deletion
      - failover
      - failure
      - maintenance
      - notification
      - recovery
      SnsTopicArn: !Ref DBSNSTopic
      SourceIds:
        - !Ref RDSDBInstance
      SourceType: db-instance
  DBParameterGroupEventSubscription:
    Type: AWS::RDS::EventSubscription
    Condition: EventSubscription
    Properties:
      EventCategories:
        - configuration change
      SnsTopicArn: !Ref DBSNSTopic
      SourceIds:
        - !Ref DBParamGroup
      SourceType: db-parameter-group
Outputs:
  DBName:
    Description: Amazon RDS (PostgreSQL) database name.
    Value: !Ref DBName
  DBUsername:
    Description: Amazon RDS (PostgreSQL) database user name.
    Value: !Ref DBUsername
  RDSEndPointAddress:
    Description: Amazon RDS (PostgreSQL) endpoint.
    Value: !GetAtt RDSDBInstance.Endpoint.Address
  RDSEndPointPort:
    Description: Amazon RDS (PostgreSQL) endpoint port.
    Value: !GetAtt RDSDBInstance.Endpoint.Port
  RDSEndPoints:
    Description: Amazon RDS (PostgreSQL) write endpoint.
    Value: !Sub ${RDSDBInstance.Endpoint.Address}:${RDSDBInstance.Endpoint.Port}/${DBName}
  RDSEncryptionKey:
    Condition: UseDatabaseEncryption
    Description: Alias of the encryption key created for Amazon RDS.
    Value: !Ref EncryptionKeyAlias
